server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_ini?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  features:
    definitions:
      - { name: "variance", typeChar: "f" }
      - { name: "mean_region", typeChar: "f" }
      - { name: "SCR", typeChar: "f" }
      - { name: "contrast", typeChar: "f" }
      - { name: "entropy", typeChar: "f" }
      - { name: "homogeneity", typeChar: "f" }
      - { name: "smoothness", typeChar: "f" }
      - { name: "skewness", typeChar: "f" }
      - { name: "kurtosis", typeChar: "f" }
      - { name: "xjy_area", typeChar: "i" }
      - { name: "peak_cell_intensity", typeChar: "f" }
      - { name: "xjy_background_intensity", typeChar: "f" }
      - { name: "tl_xs", typeChar: "i" }
      - { name: "tl_ys", typeChar: "i" }
      - { name: "widths", typeChar: "i" }
      - { name: "heights", typeChar: "i" }
  config:
    ini-path: "lib/data.ini"