server:
  port: 8081

app:
  features:
    definitions:
      - { name: "variance", typeChar: "f" }
      - { name: "mean_region", typeChar: "f" }
      - { name: "SCR", typeChar: "f" }
      - { name: "contrast", typeChar: "f" }
      - { name: "entropy", typeChar: "f" }
      - { name: "homogeneity", typeChar: "f" }
      - { name: "smoothness", typeChar: "f" }
      - { name: "skewness", typeChar: "f" }
      - { name: "kurtosis", typeChar: "f" }
      - { name: "xjy_area", typeChar: "i" }
      - { name: "peak_cell_intensity", typeChar: "f" }
      - { name: "xjy_background_intensity", typeChar: "f" }
      - { name: "tl_xs", typeChar: "i" }
      - { name: "tl_ys", typeChar: "i" }
      - { name: "widths", typeChar: "i" }
      - { name: "heights", typeChar: "i" }
  config:
    ini-path: "lib/data.ini"

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:config_database.db
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
